location: Central India
name: vided-spring-boot-app
resourceGroup: vided
type: Microsoft.App/containerApps
properties:
  managedEnvironmentId: /subscriptions/29c8eb8b-53bf-4bd1-8630-d218ffac9b86/resourceGroups/vided/providers/Microsoft.App/managedEnvironments/vided-container-env
  workloadProfileName: Consumption
  configuration:
    activeRevisionsMode: Single
    ingress:
      allowInsecure: false
      external: true
      fqdn: vided-spring-boot-app.happysand-0cd6e089.centralindia.azurecontainerapps.io
      targetPort: 8080
      traffic:
        - latestRevision: true
          weight: 100
      transport: Auto
  runningStatus: Running
  template:
    volumes:
      - name: my-azure-file-volume
        storageName: mystoragemount
        storageType: AzureFile
    containers:
      - image: pratik1188/vided-spring-boot-app:v1.1
        name: vided-spring-boot-app
        volumeMounts:
          - volumeName: my-azure-file-volume
            mountPath: /mnt
        resources:
          cpu: 1.0
          ephemeralStorage: 4Gi
          memory: 2Gi
    initContainers: null
    revisionSuffix: ""
    scale:
      maxReplicas: 1
      minReplicas: 1
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
